- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
    - name: "install required packages"
      shell: |
        sudo yum update && sudo yum upgrade -y
        sudo yum install maven git docker -y
    
    - name: "install jenkins"
      shell: |
        cd /tmp
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
        unzip -o awscliv2.zip
        ./aws/install --update

    - name: "insatll jenkins"
      shell: |
         sudo wget -O /etc/yum.repos.d/jenkins.repo \
         https://pkg.jenkins.io/rpm-stable/jenkins.repo
         sudo rpm --import https://pkg.jenkins.io/rpm-stable/jenkins.io-2026.key
         sudo yum install java-21-amazon-corretto -y
         sudo yum install jenkins -y

    - name: "enable services"
      shell: |
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo systemctl start jenkins
        sudo systemctl enable jenkins

    - name: "add group to docker"
      shell: |
        sudo gpasswd -a ec2-user docker
        sudo gpasswd -a jenkins docker 
        